### PR TITLE
remove TextFX from docs

### LINKED ISSUE #201: Addon documentation: introduction
In `intro.html` there is very prominent some quite probably outdated content:

In the first code box line 2 to 4 are:
```python
editor.pyreplace(r"^Code: ([A-Z]{4,8})", r"The code is \1")

notepad.runMenuCommand("TextFX Tools", "Delete Blank Lines")
```
But apparently in line 2 it should be `editor.rereplace`, and line 4 does not work, because there is no menu with the name “TextFX Tools” and direct command (anymore). It seems TextFX Tools has been restructured with submenus. The menu is “TextFX” and “Delete Blank Lines“ is in  a submenu “TextFX Edit”.

Which leads to the question, how to use these submenu commands of a addon/plugin in PythonScript. (If you insist I could ask this as separate issue.)

_Edit:_ Arrgh, searching for another thing I just now noticed that in `notepad.html` there is an example in section for `notepad.runMenuCommand` which has it (probably) right
```py
notepad.runMenuCommand('TextFX Edit', 'Delete Blank Lines')
```
So, the only improvement could be to add a note that `menu` in these PythonScript menu commands could itself be a submenu.

### PR DESCRIPTION
**Pull request by Ekopalypse**
closes #201

### CODE REVIEW

**Comment by alankilborn** [comment]
https://github.com/bruderstein/PythonScript/pull/368/commits/5f131e16debd86b8e4ffc714bef25c1ab6f62ec9 is a real and important change and IMO shouldn't be quietly buried in a "remove TextFX from docs" PR.

BTW, thank you for working on the PythonScript plugin!

**Comment by Ekopalypse** [comment]
>  ... is a real and important change and IMO shouldn't be quietly buried in a "remove TextFX from docs" PR.

Do not know why this happens as the PRs are from different repos.

**Comment by chcg** [comment]
@Ekopalypse Do you want to rebase the PR to contain just the relevant changes?

**Comment by Ekopalypse** [comment]
@chcg - yes, I will do that once I figure out what needs to be done, but to be honest, I don't think I can make that change this year. (Sorry, but I had to make that joke)

**Comment by Ekopalypse** [comment]
Ha, guess what - chatgpt was useful , done.

**Pull request merged**
