### PR TITLE
fixes issue #58 - set console layout to LTR

### PR DESCRIPTION
**Pull request by ClaudiaFrank**

### CODE REVIEW

**Comment by Yaron10** [comment]
That was fast!

:+1: 
Perfect. 
Thank you very much. Highly appreciated.

Allow me one question (please don't mind that :) ):

Is adding
```
LONG_PTR exstyles = GetWindowLongPtr(m_scintilla, GWL_EXSTYLE);
	if ((exstyles & WS_EX_LAYOUTRTL) == WS_EX_LAYOUTRTL)
	{
		SetWindowLongPtr(m_scintilla, GWL_EXSTYLE, exstyles & (~WS_EX_LAYOUTRTL));
        }
```
the only way to force LTR?

Can't it be achieved by removing `makeRTLResource` or passing `false` instead of `isRTL`?
(I looked at the code some months ago; `makeRTLResource` may not be the exact name).

**Comment by ClaudiaFrank** [comment]
Not sure I understand - afaik python script code does not have any isRTL call.
If you want to prevent npp from doing rtl in the first place then yes, forcing isRTL to be always false 
should prevent it from decorating a window with WS_EX_LAYOUTRTL style but from PS ...
I don't know makeRTLResource - need to search the web maybe this is a MFC way of doing it.

**Comment by ClaudiaFrank** [comment]
ooppsss - function exists in NppPlugin as well

**Comment by Yaron10** [comment]
> ooppsss - function exists in NppPlugin as well

:+1: 

I've been searching the code. :)
Could you please look into it? - It might be better to remove or modify some code.

Thank you.

**Comment by ClaudiaFrank** [comment]
The current solution seems to be the one which affects the layout of the console scintilla window. 
Changing isRTL to be always false in StaticDialog doesn't have any effect on console scintilla window.

**Comment by Yaron10** [comment]
Thank you for looking into it. And thanks again for fixing this issue.
Much appreciated.

Allow me another question:

Do we gain anything by `if ((exstyles & WS_EX_LAYOUTRTL) == WS_EX_LAYOUTRTL)`?
Is not calling `SetWindowLongPtr(m_scintilla, GWL_EXSTYLE, exstyles & (~WS_EX_LAYOUTRTL));` if NPP layout is LTR worth the extra `if`?

IOW: wouldn't `SetWindowLongPtr(m_scintilla, GWL_EXSTYLE, exstyles & (~WS_EX_LAYOUTRTL));` be enough or better?

I don't know. What do you think?

**Comment by ClaudiaFrank** [comment]
Imho - taking care that only WS_EX_LAYOUTRTL is removed if set is worth it

**Pull request merged**
